### ISSUE TITLE
Collapsing documentation comments in PHP file

### ISSUE THREAD

**Issue by B-Yasmina** [Etsi0/class-collapse#11]
`php` is listed as a supported language in `class-collapse.supportedLanguages`, however, I can't seem to make it work for documentation comment lines.

I'd like to turn
```php
    /**
    * Function description
    * @param type var desc
    * @return type desc
    */
```
into
```php
    /**...doc...*/
```
Is there something wrong in my settings?

```json
    "class-collapse.regex": "(^ *\\/\\*\\*)([^!][.\\s\\t\\S\\n\\r]*?)(\\*\\/)",
    "class-collapse.collapsedText": "...doc...",
    "class-collapse.regexGroups": [
        2
    ],
    "class-collapse.supportedLanguages": [
        "html",
        "javascript",
        "markdown",
        "php"
    ],
    "class-collapse.classCollapseToggle": true
```

Or is it simply not possible with this extension ?

Thank you in advance.

**Comment by Etsi0** [comment]
Hello,

Here is a regex that should work: [regex101.com](https://regex101.com/r/XqKpqc/1).
Additionally, here is a visualization of the regex: [regex-vis.com](https://regex-vis.com/?r=%28%5E%5Cs*%3F%5C%2F%5C*%5C*%29%28%5B%5Cs%5CS%5D*%3F%29%28%5C*%5C%2F%29).

Thank you for using Class Collapse and I hope you have a good rest of your day or night.
// Albin

**Comment by B-Yasmina** [comment]
That indeed solved it, thank you.

However, is it intentional that all lines haven't really collapsed? The text has been replaced, not the \n.

```php
/**...doc...

*/
```

**Comment by Etsi0** [comment]
Hello again,
As far as i know it's not possible to remove lines :/
